# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e4674084373039c75c7c73ea476ea1338f4aa50ce7754fd89044cebd70a778d3cd5e00cb4d7870d1c8f79a48276db0816d648ea843c1a4beabbe782ec6a2629

test:
  secret_key_base: d2e1182b7237da61876292dc24ef4b56b789b17d74caee3d93dcdbd4034ffe1324719f7bac1ea5cfdda0f8320d390bfa2aa2e121ae1299dae42434413540654e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
